# gitea-action-composite/.gitea/action/publish.yaml

name: 'Build and Push Docker Image'
description: 'A reusable Gitea action to log in, build, and push a Docker image to a specified registry.'

# Define the inputs this action will accept
inputs:
  registry:
    description: 'The container registry to push the image to.'
    required: true
  image_name:
    description: 'The name for the Docker image.'
    required: true
  username:
    description: 'Username for logging into the container registry.'
    required: true
  password:
    description: 'Password or token for logging into the container registry.'
    required: true
  build-context:
    description: 'The build context path for the Docker build.'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    # Uses the `docker/login-action` action to log in to the Container registry.
    - name: Log in to the Container registry
      uses: https://github.com/docker/login-action@master
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    # Extracts tags and labels that will be applied to the specified image.
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: https://github.com/docker/metadata-action@master
      with:
        images: ${{ inputs.registry }}/${{ inputs.image_name }}

    # Builds the image based on the repository's Dockerfile and pushes it to the registry.
    - name: Build and push Docker image
      id: push
      uses: https://github.com/docker/build-push-action@master
      with:
        context: ${{ inputs.build-context }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}